# Funding options for Vibe.UI
# You can add your preferred funding platforms here

github: [dieshen] # Uncomment and add your GitHub Sponsors username
# patreon: your-patreon  # Uncomment and add your Patreon username
# ko_fi: your-kofi  # Uncomment and add your Ko-fi username
custom: ["https://buymeacoffee.com/dieshen"]
