using Vibe.CSS.Emitter;
using Vibe.CSS.Generator;

namespace Vibe.CSS.Tests.Emitter;

public class CssEmitterTests
{
    private readonly CssEmitter _emitter = new();

    #region GenerateCss Tests

    [Fact]
    public void GenerateCss_SingleClass_GeneratesValidCss()
    {
        var classes = new[] { "vibe-flex" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        Assert.Contains(".vibe-flex", css);
        Assert.Contains("display: flex", css);
    }

    [Fact]
    public void GenerateCss_MultipleClasses_GeneratesAllRules()
    {
        var classes = new[] { "vibe-flex", "vibe-p-4", "vibe-bg-primary" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        Assert.Contains(".vibe-flex", css);
        Assert.Contains(".vibe-p-4", css);
        Assert.Contains(".vibe-bg-primary", css);
    }

    [Fact]
    public void GenerateCss_DuplicateClasses_DeduplicatesCorrectly()
    {
        var classes = new[] { "vibe-flex", "vibe-flex", "vibe-flex" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        // Should only contain one instance
        var count = css.Split(".vibe-flex").Length - 1;
        Assert.Equal(1, count);
    }

    [Fact]
    public void GenerateCss_UnknownClasses_IgnoredGracefully()
    {
        var classes = new[] { "vibe-flex", "unknown-class", "vibe-p-4" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        Assert.Contains(".vibe-flex", css);
        Assert.Contains(".vibe-p-4", css);
        Assert.DoesNotContain(".unknown-class", css);
    }

    [Fact]
    public void GenerateCss_EmptyClasses_ReturnsHeaderOnly()
    {
        var classes = Array.Empty<string>();

        var css = _emitter.GenerateCss(classes, includeBase: false);

        Assert.Contains("Generated by Vibe.CSS", css);
        Assert.Contains("Utility Classes", css);
    }

    #endregion

    #region Media Query Grouping Tests

    [Fact]
    public void GenerateCss_ResponsiveClasses_GroupedByBreakpoint()
    {
        var classes = new[] { "sm:vibe-flex", "md:vibe-flex", "lg:vibe-flex" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        // Check breakpoints are present
        Assert.Contains("@media (min-width: 640px)", css);
        Assert.Contains("@media (min-width: 768px)", css);
        Assert.Contains("@media (min-width: 1024px)", css);
    }

    [Fact]
    public void GenerateCss_MixedClasses_BaseBeforeMedia()
    {
        var classes = new[] { "vibe-flex", "sm:vibe-hidden", "vibe-p-4" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        // Base classes should appear before media queries
        var baseFlexIndex = css.IndexOf(".vibe-flex");
        var mediaIndex = css.IndexOf("@media");

        Assert.True(baseFlexIndex < mediaIndex, "Base classes should appear before media queries");
    }

    [Fact]
    public void GenerateCss_BreakpointOrdering_MobileFirst()
    {
        var classes = new[] { "lg:vibe-flex", "sm:vibe-flex", "xl:vibe-flex", "md:vibe-flex" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        var smIndex = css.IndexOf("640px");
        var mdIndex = css.IndexOf("768px");
        var lgIndex = css.IndexOf("1024px");
        var xlIndex = css.IndexOf("1280px");

        // Mobile-first: sm < md < lg < xl
        Assert.True(smIndex < mdIndex, "sm should come before md");
        Assert.True(mdIndex < lgIndex, "md should come before lg");
        Assert.True(lgIndex < xlIndex, "lg should come before xl");
    }

    #endregion

    #region IncludeBase Tests

    [Fact]
    public void GenerateCss_IncludeBaseTrue_ContainsBaseStyles()
    {
        var classes = new[] { "vibe-flex" };

        var css = _emitter.GenerateCss(classes, includeBase: true);

        // Base CSS should include CSS variables (from vibe-base.css)
        Assert.Contains("--vibe-", css);
    }

    [Fact]
    public void GenerateCss_IncludeBaseFalse_NoBaseStyles()
    {
        var classes = new[] { "vibe-flex" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        // Should not include variable declarations from base
        // Only utility classes should be present
        Assert.Contains(".vibe-flex", css);
    }

    #endregion

    #region GenerateForContent Tests

    [Fact]
    public void GenerateForContent_ExtractsAndGenerates()
    {
        var content = @"<div class=""vibe-flex vibe-gap-4"">Content</div>";

        var css = _emitter.GenerateForContent(content, includeBase: false);

        Assert.Contains(".vibe-flex", css);
        Assert.Contains(".vibe-gap-4", css);
    }

    [Fact]
    public void GenerateForContent_BlazorSyntax_Works()
    {
        var content = @"
            <div class=""vibe-flex"">
                <span @class=""vibe-text-sm"">Text</span>
            </div>";

        var css = _emitter.GenerateForContent(content, includeBase: false);

        Assert.Contains(".vibe-flex", css);
        Assert.Contains(".vibe-text-sm", css);
    }

    #endregion

    #region GetStats Tests

    [Fact]
    public void GetStats_AllKnownClasses_AllGenerated()
    {
        var classes = new[] { "vibe-flex", "vibe-p-4", "vibe-bg-primary" };

        var stats = _emitter.GetStats(classes);

        Assert.Equal(3, stats.TotalClasses);
        Assert.Equal(3, stats.GeneratedClasses);
        Assert.Empty(stats.UnknownClasses);
    }

    [Fact]
    public void GetStats_MixedClasses_TracksUnknown()
    {
        var classes = new[] { "vibe-flex", "unknown-one", "vibe-p-4", "unknown-two" };

        var stats = _emitter.GetStats(classes);

        Assert.Equal(4, stats.TotalClasses);
        Assert.Equal(2, stats.GeneratedClasses);
        Assert.Equal(2, stats.UnknownCount);
        Assert.Contains("unknown-one", stats.UnknownClasses);
        Assert.Contains("unknown-two", stats.UnknownClasses);
    }

    [Fact]
    public void GetStats_EmptyClasses_ReturnsZeros()
    {
        var classes = Array.Empty<string>();

        var stats = _emitter.GetStats(classes);

        Assert.Equal(0, stats.TotalClasses);
        Assert.Equal(0, stats.GeneratedClasses);
        Assert.Empty(stats.UnknownClasses);
    }

    #endregion

    #region CSS Output Format Tests

    [Fact]
    public void GenerateCss_Header_ContainsTimestamp()
    {
        var classes = new[] { "vibe-flex" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        Assert.Contains("Generated at:", css);
        Assert.Contains("UTC", css);
    }

    [Fact]
    public void GenerateCss_SelectorEscaping_HandlesSpecialChars()
    {
        var classes = new[] { "hover:vibe-bg-primary", "vibe-w-1/2", "vibe-p-[20px]" };

        var css = _emitter.GenerateCss(classes, includeBase: false);

        // Selectors with special chars should be escaped
        Assert.Contains(@"hover\:vibe-bg-primary:hover", css);
        Assert.Contains(@"vibe-w-1\/2", css);
        Assert.Contains(@"vibe-p-\[20px\]", css);
    }

    #endregion

    #region Custom Config Tests

    [Fact]
    public void Constructor_CustomConfig_AppliesPrefix()
    {
        var config = new VibeConfig { Prefix = "tw" };
        var emitter = new CssEmitter(config);

        var classes = new[] { "tw-flex", "tw-p-4" };
        var css = emitter.GenerateCss(classes, includeBase: false);

        Assert.Contains(".tw-flex", css);
        Assert.Contains(".tw-p-4", css);
    }

    #endregion
}
