name: Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - Component documentation
        - Getting started guide
        - API reference
        - Examples/tutorials
        - README
        - Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: Link to the documentation page (if applicable)
      placeholder: https://docs.vibe-ui.com/components/button

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe what's wrong or missing in the documentation
      placeholder: The Button component docs don't mention the Size property...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should this be improved?
      placeholder: Add a section explaining the Size property with examples

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots
