name: Feature Request
description: Suggest a new feature or enhancement for Vibe.UI
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: Add a DateTimePicker component that...
    validations:
      required: true

  - type: dropdown
    id: component-type
    attributes:
      label: What type of feature is this?
      options:
        - New component
        - Component enhancement
        - CLI feature
        - Documentation
        - Theming
        - Developer experience
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples from other libraries or designs that illustrate this feature
      placeholder: |
        Similar to shadcn/ui's DatePicker:
        https://ui.shadcn.com/docs/components/date-picker

  - type: textarea
    id: api
    attributes:
      label: Proposed API (if applicable)
      description: Show how you envision the API/usage
      render: razor
      placeholder: |
        <DateTimePicker
            Value="@selectedDate"
            ValueChanged="@OnDateChanged"
            Format="yyyy-MM-dd" />

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with documentation
        - label: I can help with testing

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or information about the feature request here.
